package com.linroid.viewit.utils

/**
 * @author linroid <linroid@gmail.com>
 * @since 04/03/2017
 */

const val EVENT_CLICK_PATH_SETTINGS = "CLICK_PATH_SETTINGS"
const val EVENT_CLICK_PATH_SETTINGS_NO_IMAGE = "CLICK_PATH_SETTINGS_NO_IMAGE"
const val EVENT_CLICK_PATH_EDIT = "CLICK_PATH_EDIT"
const val EVENT_CLICK_PATH_DELETE = "CLICK_PATH_DELETE"
const val EVENT_CLICK_PATH_ADD = "CLICK_PATH_ADD"

const val EVENT_SORT_IMAGE = "SORT_IMAGE"
const val EVENT_FILTER_IMAGE = "FILTER_IMAGE"

const val EVENT_CLICK_IMAGE_SORT = "CLICK_IMAGE_SORT"
const val EVENT_CLICK_IMAGE_FILTER = "CLICK_IMAGE_FILTER"

const val EVENT_CLICK_JUMP_TO_IMAGES = "CLICK_JUMP_TO_IMAGES"

const val EVENT_LIST_APP = "LIST_APP"

const val EVENT_SCAN_IMAGE = "SCAN_IMAGE"
const val EVENT_DELETE_FAVORITE = "DELETE_FAVORITE"
const val EVENT_ADD_FAVORITE = "ADD_FAVORITE"
const val EVENT_SAVE_FAVORITE = "SAVE_FAVORITE"


const val EVENT_CLICK_IMAGE_DETAIL = "CLICK_IMAGE_DETAIL"
const val EVENT_SHARE_IMAGE = "SHARE_IMAGE"
const val EVENT_DELETE_IMAGE = "DELETE_IMAGE"
const val EVENT_SAVE_IMAGE = "SAVE_IMAGE"


const val EVENT_CLICK_APP = "CLICK_APP"
const val EVENT_CLICK_APP_DETAIL = "CLICK_APP_DETAIL"
const val EVENT_CLICK_LAUNCH_APP = "CLICK_LAUNCH_APP"
const val EVENT_CLICK_FAVORITE = "CLICK_FAVORITE"
const val EVENT_CLICK_CLOUD_FAVORITE = "CLICK_CLOUD_FAVORITE"
const val EVENT_CLICK_TREE = "CLICK_TREE"
const val EVENT_VIEW_IMAGE = "VIEW_IMAGE"

const val EVENT_CLICK_FEEDBACK = "CLICK_FEEDBACK"

// 关于页面
const val EVENT_CLICK_ABOUT = "CLICK_ABOUT"
const val EVENT_CLICK_ABOUT_DONATE = "CLICK_ABOUT_DONATE"
const val EVENT_CLICK_ABOUT_DEVELOPER = "CLICK_ABOUT_DEVELOPER"
const val EVENT_CLICK_ABOUT_SHARE = "CLICK_ABOUT_SHARE"
const val EVENT_CLICK_ABOUT_OPENSOURCE = "CLICK_ABOUT_OPENSOURCE"


const val EVENT_BATCH_SHARE_IMAGE = "BATCH_SHARE_IMAGE"
const val EVENT_BATCH_DELETE_IMAGE = "BATCH_DELETE_IMAGE"
const val EVENT_BATCH_SAVE_IMAGE = "BATCH_SAVE_IMAGE"